version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 20
    target-branch: "master"
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "deps"