name: Java CI with Maven

permissions:
  contents: write
  actions: read
  security-events: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24-dind
        ports:
          - 2375:2375
        options: >-
          --privileged
          --storage-driver overlay2
        env:
          DOCKER_TLS_CERTDIR: ""

    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""
      TESTCONTAINERS_RYUK_DISABLED: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify Java & Docker
        run: |
          java -version
          javac -version
          echo "JAVA_HOME: $JAVA_HOME"
          docker version
          docker info

      - name: Build & Test
        run: |
          mvn -U -T1C clean verify -Dmaven.compiler.source=21 -Dmaven.compiler.target=21

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          settings-file: pom.xml
