name: Java CI with Maven

permissions:
  contents: write
  actions: read
  security-events: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify Java & Docker
        run: |
          java -version
          javac -version
          echo "JAVA_HOME: $JAVA_HOME"
          docker version
          docker info

      - name: Build & Test
        run: |
          mvn -U -T1C clean verify

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          settings-file: pom.xml
