name: Quality Monitor

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      - name: Build, Test, Lint, Security, Coverage
        run: mvn -B -ntp clean verify

      - name: Upload quality reports (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports
          path: |
            recrutech-services/target/site/jacoco-aggregate/**
            **/target/site/**